networks:
  app-net:
    driver: bridge

services:
  api-gateway-service:
    build:
      context: ./api-gateway-service
      dockerfile: Dockerfile
    image: api-gateway-service
    ports:
      - "8081:8081"
    networks:
      - app-net
    depends_on:
      property-config-server:
        condition: service_healthy
      eureka-discovery-server:
        condition: service_healthy
  eureka-discovery-server:
    build:
      context: ./eureka-discovery-server
      dockerfile: Dockerfile
    image: eureka-discovery-server
    ports:
      - "8761:8761"
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
  app-monitoring-admin-server:
    build:
      context: ./app-monitoring-admin-server
      dockerfile: Dockerfile
    image: app-monitoring-admin-server
    ports:
      - "8087:8087"
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8087/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      property-config-server:
        condition: service_healthy
      eureka-discovery-server:
        condition: service_healthy
  inventory-management-service:
    build:
      context: ./inventory-management-service
      dockerfile: Dockerfile
    image: inventory-management-service
    ports:
      - "8085:8085"
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      - KEYCLOAK_AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
    depends_on:
      property-config-server:
        condition: service_healthy
      eureka-discovery-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
  order-management-service:
    build:
      context: ./order-management-service
      dockerfile: Dockerfile
    image: order-management-service
    ports:
      - "8084:8084"
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      - KEYCLOAK_AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
    depends_on:
      property-config-server:
        condition: service_healthy
      eureka-discovery-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
  payment-management-service:
    build:
      context: ./payment-management-service
      dockerfile: Dockerfile
    image: payment-management-service
    ports:
      - "8086:8086"
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      - KEYCLOAK_AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
    depends_on:
      property-config-server:
        condition: service_healthy
      eureka-discovery-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
  product-catalog-service:
    build:
      context: ./product-catalog-service
      dockerfile: Dockerfile
    image: product-catalog-service
    ports:
      - "8083:8083"
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      - KEYCLOAK_AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
    depends_on:
      property-config-server:
        condition: service_healthy
      eureka-discovery-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
  property-config-server:
    build:
      context: ./property-config-server
      dockerfile: Dockerfile
    image: property-config-server
    ports:
      - "8888:8888"
    networks:
      - app-net
    depends_on:
      eureka-discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
  user-management-service:
    build:
      context: ./user-management-service
      dockerfile: Dockerfile
    image: user-management-service
    ports:
      - "8082:8082"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - SPRING_APPLICATION_NAME=user-management-service
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      - KEYCLOAK_AUTH_SERVER_URL=${KEYCLOAK_AUTH_SERVER_URL}
    networks:
      - app-net
    depends_on:
      property-config-server:
        condition: service_healthy
      eureka-discovery-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - app-net