server:
  port: 8888

spring:
  application:
    name: property-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RRV2018/e-commerce-application.git
          username: ${app.git.username}
          password: ${app.git.password}
          default-label: main
          refresh-rate: 0
          search-paths: config_properties
  boot:
    admin:
      client:
        instance:
          hostname: localhost
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery-server:8761/eureka
    instance:
      preferIpAddress: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health
