server:
  port: 8087

spring:
  application:
    name: app-monitoring-admin-server
  security:
    user:
      name: admin
      password: admin123
  boot:
    admin:
      discovery:
        ignored-services:
          - app-monitoring-admin-server
      client:
        enabled: false
        instance:
          service-base-url: http://localhost:${server.port}
          management-base-url: http://localhost:${server.port}
  cloud:
    config:
      enabled: false

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true   # âœ… CORRECT LOCATION

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"