server:
  port: 8761

spring:
  application:
    name: spring-boot-eureka-server

  cloud:
    config:
      enabled: false
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000    # 2 sec
        multiplier: 1.5
        max-interval: 10000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false