spring:
  application:
    name: payment-management-service
  config:
    import: configserver:http://property-config-server:8888

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000    # 2 sec
        multiplier: 1.5
        max-interval: 10000